/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class ListaSequencialSimples {
    Object[] area;
    int len;
    final int defcap = 8;

    public ListaSequencialSimples() {
        area = new Object[defcap];
        this.len = 0;
    }

    public void adiciona(Object valor) {
        if (len < area.length) {
            area[len] = valor;
            len++;
        } else {
            throw new ArrayIndexOutOfBoundsException("Lista cheia!");
        }
    }

    public void remove(int indice) {
        if (indice < 0 || indice >= len) {
            throw new IndexOutOfBoundsException("Indice inválido!");
        }
        Object valorRemovido = area[indice];

        area[indice] = area[len - 1];
        len--;
    }

    public boolean esta_vazia() {
        return len == 0;
    }

    public int comprimento() {
        return len;
    }

    public int capacidade() {
        return area.length;
    }

    public void limpa() {
        for (int i = 0; i < area.length; i++) {
            area[i] = null;
        }

        len = 0;
    }

    public Object obtem(int indice) {
        if (indice < 0 || indice >= len) {
            throw new IndexOutOfBoundsException("Indice inválido!");
        }
        return area[indice];
    }

    public int procura(Object valor) {
        for (int i = 0; i < len; i++) {
            if (area[i].equals(valor)) {
                return i;
            }
        }
        return -1;
    }

    public void ordena() {
        for (int i = 0; i < len - 1; i++) {
            Comparable x1 = (Comparable) this.area[i];
            Comparable x2 = (Comparable) this.area[i + 1];
            if (x1.compareTo(x2) > 0) {
                Object armazena = area[i];
                area[i] = area[i +1];
                area[i + 1] = armazena;
            }
        }
    }

    // mescla duas sequÊncias contidas na área d armazenamento de lista (em "area")
    void mescla(int pos1, int meio, int pos2, Object[] subsesq) {
    }

    void oderna_mescla(int pos1, int pos2, Object[] subseq) {
        if (pos2 - pos1 > 0) {
            int meio = pos1 + ((pos2 - pos1) / 2);
        }

    }

    public void orderna_mescla() {
        Object[] area_ordenada = new Object[area.length];
        oderna_mescla(0, len, new Object[len]);
        area = area_ordenada;
    }
}